[package]
name = "plotting"
version = "0.1.0"
authors = ["Markus <markus.ydreskog@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version="*", features=["canvas"]}


